language: node_js

node_js:
- 0.10

addons:
  firefox: '28.0'

before_script:
- export DISPLAY=:99.0
- export SLIMERJSLAUNCHER=$(which firefox)
- export DISPLAY=:99.0
- export PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
- sh -e /etc/init.d/xvfb start
- npm install -g gulp
- ./test/install-slimer.sh
- ./test/screenshot.sh
- ./test/gh-pages.sh

env:
  global:
    secure: ei8N8RM/03qdTCFmjyy4hjOVqG9SfKkFr3URHVa0XVYk/DtRUbEd5yA8XJ1xVKGaQwq3gHxCjTQii6gX+YcJ1AvSUXuSkniw6ElXwieHgHBlptxU4d/61enzxM5lUIxjehg9EGidb4OiCmVUjf8mQFfw/73UPoZe+CQplbZaIKA=
